### ISSUE TITLE
cannot import/save revu projects in PhpStorm 9

### ISSUE THREAD

**Issue by tomi20v** [syllant/idea-plugin-revu#39]
it just gives a file already exists error
no problem in 8 but this started happening in EAP and now for 9 also
to reproduce: try importing a revu xml. click OK
one should be able to create a new review but then cannot change it
actual error:

Failed to save review 'fix_utf8_errors': java.io.IOException: '/[path_to]/fix_utf8_errors.xml' already exists in VFS

**Comment by syllant** [comment]
@tomi20v I've done a quick fix but I've not published a new build yet, I don't have time to investigate the exact cause. Can you try to build a new JAR from source? Otherwise I'll give you mine.

**Comment by tomi20v** [comment]
I can build your source if that helps but not today.
however yesterday I managed to do the exact same fix, just checked your
commit. already tested fine on 2 machines.


2015-07-20 23:20 GMT+02:00 Sylvain FRANÇOIS <notifications@github.com>:

**Comment by syllant** [comment]
OK, thanks for letting me know. This plugin becomes quite outdated regarding last changes in the IDE or the API. It would deserve lots of changes, but I'll probably publish a release fix for this bug.

**Comment by syllant** [comment]
2.7.2 published
